<?php
/**
 * @file
 * sponsor_plans.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function sponsor_plans_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'Sponsors plan',
  'log' => 'Valid until october 31',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '0db1d93c-98e1-4b98-b7cf-9e14d4c6e92e',
  'type' => 'sponsors_plan',
  'language' => 'und',
  'created' => 1441825820,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '38437837-ebc4-4dd8-93d7-fce07f20fba1',
  'revision_uid' => 1,
  'body' => array(),
  'field_booth' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_five_minutes_open_session' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_footer_web' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_logo_on_t_shirt' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_main_speaker_start_and_fin' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_printed_signals' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_social_networks_mention' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_space_available' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_sponsors_page' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_sponsorship_level' => array(
    'und' => array(
      0 => array(
        'tid' => 1,
      ),
    ),
  ),
  'field_us_price' => array(
    'und' => array(
      0 => array(
        'amount' => 300000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-09-09 16:10:20 -0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Sponsors plan',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '9da113ac-227b-42a8-8f84-2c4e72d97108',
  'type' => 'sponsors_plan',
  'language' => 'und',
  'created' => 1441826248,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '43b91223-f845-4656-b372-1acf6f4071bf',
  'revision_uid' => 1,
  'body' => array(),
  'field_booth' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_five_minutes_open_session' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_footer_web' => array(
    'und' => array(
      0 => array(
        'value' => 3,
      ),
    ),
  ),
  'field_logo_on_t_shirt' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_main_speaker_start_and_fin' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_printed_signals' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_social_networks_mention' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_space_available' => array(),
  'field_sponsors_page' => array(
    'und' => array(
      0 => array(
        'value' => 3,
      ),
    ),
  ),
  'field_sponsorship_level' => array(
    'und' => array(
      0 => array(
        'tid' => 4,
      ),
    ),
  ),
  'field_us_price' => array(
    'und' => array(
      0 => array(
        'amount' => 50000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-09-09 16:17:28 -0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Sponsors plan',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '7f1cb3ed-1674-46f0-882b-4b41974229ea',
  'type' => 'sponsors_plan',
  'language' => 'und',
  'created' => 1441825963,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '87e54b61-7ff5-4e14-abed-d5b6376cb53f',
  'revision_uid' => 1,
  'body' => array(),
  'field_booth' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_five_minutes_open_session' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_footer_web' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_logo_on_t_shirt' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_main_speaker_start_and_fin' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_printed_signals' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_social_networks_mention' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_space_available' => array(
    'und' => array(
      0 => array(
        'value' => 3,
      ),
    ),
  ),
  'field_sponsors_page' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_sponsorship_level' => array(
    'und' => array(
      0 => array(
        'tid' => 2,
      ),
    ),
  ),
  'field_us_price' => array(
    'und' => array(
      0 => array(
        'amount' => 200000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-09-09 16:12:43 -0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Sponsors plan',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'bcae4ee2-d309-4a0b-a09d-f3a92e4ed659',
  'type' => 'sponsors_plan',
  'language' => 'und',
  'created' => 1441826339,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'aebd88b1-7fda-4a80-8441-e5fa2ccb63a5',
  'revision_uid' => 1,
  'body' => array(),
  'field_booth' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_five_minutes_open_session' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_footer_web' => array(
    'und' => array(
      0 => array(
        'value' => 3,
      ),
    ),
  ),
  'field_logo_on_t_shirt' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_main_speaker_start_and_fin' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_printed_signals' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_social_networks_mention' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_space_available' => array(),
  'field_sponsors_page' => array(
    'und' => array(
      0 => array(
        'value' => 4,
      ),
    ),
  ),
  'field_sponsorship_level' => array(
    'und' => array(
      0 => array(
        'tid' => 5,
      ),
    ),
  ),
  'field_us_price' => array(
    'und' => array(
      0 => array(
        'amount' => 25000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-09-09 16:18:59 -0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Sponsors plan',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'cb5660c2-295f-4335-920e-4995000d7b75',
  'type' => 'sponsors_plan',
  'language' => 'und',
  'created' => 1441826075,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'dfb4c878-f604-410c-b87d-360231991d5c',
  'revision_uid' => 1,
  'body' => array(),
  'field_booth' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_five_minutes_open_session' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_footer_web' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_logo_on_t_shirt' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_main_speaker_start_and_fin' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_printed_signals' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_social_networks_mention' => array(
    'und' => array(
      0 => array(
        'value' => 1,
      ),
    ),
  ),
  'field_space_available' => array(
    'und' => array(
      0 => array(
        'value' => 5,
      ),
    ),
  ),
  'field_sponsors_page' => array(
    'und' => array(
      0 => array(
        'value' => 2,
      ),
    ),
  ),
  'field_sponsorship_level' => array(
    'und' => array(
      0 => array(
        'tid' => 3,
      ),
    ),
  ),
  'field_us_price' => array(
    'und' => array(
      0 => array(
        'amount' => 100000,
        'currency_code' => 'USD',
        'data' => array(
          'components' => array(),
        ),
      ),
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2015-09-09 16:14:35 -0300',
);
  return $nodes;
}
